export const LOGIN_USER_PENDING = 'LOGIN_USER_PENDING';
export const LOGIN_USER_FULFILLED = 'LOGIN_USER_FULFILLED';
export const LOGIN_USER_REJECTED = 'LOGIN_USER_REJECTED';

export const REGISTER_USER_PENDING = 'REGISTER_USER_PENDING';
export const REGISTER_USER_FULFILLED = 'REGISTER_USER_FULFILLED';
export const REGISTER_USER_REJECTED = 'REGISTER_USER_REJECTED';

export const ADD_TO_CART_PENDING = 'ADD_TO_CART_PENDING';
export const ADD_TO_CART_FULFILLED = 'ADD_TO_CART_FULFILLED';
export const ADD_TO_CART_REJECTED = 'ADD_TO_CART_REJECTED';

export const FETCH_CART_PENDING = 'FETCH_CART_PENDING';
export const FETCH_CART_FULFILLED = 'FETCH_CART_FULFILLED';
export const FETCH_CART_REJECTED = 'FETCH_CART_REJECTED';

export const UPDATING_CART_PENDING = 'UPDATING_CART_PENDING';
export const UPDATING_CART_FULFILLED = 'UPDATING_CART_FULFILLED';
export const UPDATING_CART_REJECTED = 'UPDATING_CART_REJECTED';

export const DELETE_CART_ITEM_PENDING = 'DELETE_CART_ITEM_PENDING';
export const DELETE_CART_ITEM_FULFILLED = 'DELETE_CART_ITEM_FULFILLED';
export const DELETE_CART_ITEM_REJECTED = 'DELETE_CART_ITEM_REJECTED';

export const MAKE_PAYMENT_PENDING = "MAKE_PAYMENT_PENDING";
export const MAKE_PAYMENT_FULFILLED = "MAKE_PAYMENT_FULFILLED";
export const MAKE_PAYMENT_REJECTED = "MAKE_PAYMENT_REJECTED";

export const CLEAR_ERROR_MESSAGE = 'CLEAR_ERROR_MESSAGE';